# Merge the files generated by the Travis log parser and the GHTorrent
# data extractor.

library(data.table)
library(plyr)

gh <- fread('build_data_extraction.csv')
tr <- fread('merged_travis.csv')
final <- merge(tr, gh, by.x = 'tr_build_id', by.y = 'tr_build_id')

final$tr_original_commit.y <- NULL
final$commit <- NULL
final$started_at <- NULL
final$event_type <- NULL
final$pull_req <- NULL
final$branch <- NULL

final <- rename(final, c('tr_original_commit.x' = 'tr_original_commit',
                         'duration' = 'tr_duration',
                         'status' = 'tr_status',
                         'jobs' = 'tr_jobs',
                         'gh_test_lines_per_kloc' =  'gh_test_lines',
                         'gh_test_cases_per_kloc' = 'gh_test_cases',
                         'gh_asserts_cases_per_kloc' = 'gh_asserts'
                         ))

fwrite(final, 'final-2017-02-02.csv')

