require_relative 'ghtorrent_extractor/ghtorrent_extractor'
require_relative 'ghtorrent_extractor/go'
require_relative 'ghtorrent_extractor/java'
require_relative 'ghtorrent_extractor/python'
require_relative 'ghtorrent_extractor/ruby'
